title: Gluten Free Brewing Guild
description: Resources for 100% naturally gluten-free beer and brewing
remote_theme: just-the-docs/just-the-docs

url: "https://gfbrewingguild.github.io"

search_enabled: true

logo: "/assets/images/GFBG_logo.png"

aux_links:
  "Join the Discord":
    - "https://discord.gg/6TTprwJPbp"
  "Open Discord":
    - "https://discord.com/channels/1199470407753928744"
footer_content: "Copyright © Gluten Free Brewing Guild. All rights reserved."
